_target_: information_safety.algorithms.dataset_handlers.evilmath.EvilMathHandler
max_length: 1024
batch_size: 4
max_new_tokens: 512
generations_dir: ${oc.env:GENERATIONS_DIR,/network/scratch/b/brownet/information-safety/generations}
dataset_name: evilmath
max_examples: null
train_data_path: null
corpus_fraction: 0.0
