defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_


model_checkpoint:
  monitor: "val/performance"
  mode: "max"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionally always save model from last epoch
  verbose: False
  dirpath: "${hydra:runtime.output_dir}/checkpoints"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False


early_stopping:
  monitor: "val/performance"
  patience: 5
  mode: "max"

model_summary:
  max_depth: 2

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor

device_utilisation:
  _target_: lightning.pytorch.callbacks.DeviceStatsMonitor
throughput:
  _target_: information_safety.algorithms.callbacks.samples_per_second.MeasureSamplesPerSecondCallback
