_target_: information_safety.algorithms.networks.fcnet.FcNet
output_dims: ${instance_attr:datamodule.num_classes}
input_shape: ${instance_attr:datamodule.dims}
hparams:
  _target_: information_safety.algorithms.networks.fcnet.HParams
